# Permalinks
permalink:           pretty

# Setup
title:               Weiyu Tong
tagline:             A Great Data Science Blog
url:                 http://weiyutong.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Weiyu Tong
  url:               https://twitter.com/weeeyuuu
  email:             weiyutongguy@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/weiyutong

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
